; clip_.inc
;
; License CC0 PUBLIC DOMAIN
;
; To the extent possible under law, Mark J. Olesen has waived all copyright 
; and related or neighboring rights to ow32svga Library. This work is published 
; from: United States.

clip struct
    clip_x1                      dd ? 
    clip_y1                      dd ? 
    clip_x2                      dd ?
    clip_y2                      dd ? 
clip ends
